version: '3'

services:
  db:
    image: postgres:14.3
    container_name: teslodb
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_DB: ${DB_POSTGRES_NAME}
    ports:
      - 5434:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data